name: benchmark-dotnet-sql2025

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  Path_Tests: './src/BenchmarkingDapperEFCoreCRMSqlServer'
  Path_ArtifactsBenchmarking: './src/BenchmarkingDapperEFCoreCRMSqlServer/BenchmarkDotNet.Artifacts/results'
  ArtifactBenchmarkingHtml: 'BenchmarkingDapperEFCoreCRMSqlServer.Tests.CRMTests-report.html'
  ArtifactBenchmarkingMarkdown: 'BenchmarkingDapperEFCoreCRMSqlServer.Tests.CRMTests-report-github.md'
  NoContatosPorCompanhia: '2'

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Exibir versoes instaladas do .NET SDK
        run: |
          echo '*** SDKs do .NET instalados ***'
          dotnet --list-sdks
          echo '*** Versão assumida como default para o .NET ***'
          dotnet --version

      - name: Setup .NET 10 Release Candidate 1
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.100-rc.1.25451.107'

      - name: Exibir versoes instaladas do .NET SDK (parte 2)
        run: |
          echo '*** SDKs do .NET instalados ***'
          dotnet --list-sdks
          echo '*** Versão assumida como default para o .NET ***'
          dotnet --version

      - name: Exibir configuracao com o numero de Contatos a serem criados por Empresa/Companhia
        run: |
          echo 'No. de Contatos a serem criados para cada registro de Empresa/Companhia:'
          echo ''
          echo ${{ env.NoContatosPorCompanhia }}
          echo ''

      - name: Executar benchmarking com testes de performance comparando alternativas
        run: |
          cd ${{ env.Path_Tests }}
          echo '*** Arquivos no diretorio do projeto ***'
          pwd
          echo ''
          ls
          echo ''
          echo 'Iniciando a execucao dos testes...'
          echo ''
          dotnet run --filter BenchmarkingDapperEFCoreCRMSqlServer.Tests.* -c Release
        env:
          NumeroContatosPorCompanhia: ${{ env.NoContatosPorCompanhia }}

      - name: Exibir containers apos 20 segundos
        run: |
          sleep 20s
          docker ps -a

      - name: Exibir arquivos gerados como resultado dos testes
        run: |
          cd ${{ env.Path_ArtifactsBenchmarking }}
          pwd
          ls

      - uses: dtinth/markdown-report-action@v1
        with:
          name: Benchmarking .NET 10 X SQL Server 2025
          title: Benchmarking .NET 10 X SQL Server 2025 - ADO, Dapper, Dapper.Contrib, EF Core e Stored Procedures
          body-file: ${{ env.Path_ArtifactsBenchmarking }}/${{ env.ArtifactBenchmarkingMarkdown }}